---
title: "Deployment of GenMon Instance"
author: "Peter von Rohr"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Disclaimer
The deployment of a new GenMon Instance is described. The description is split into the following parts

* OS: decide which user should be running and adminstrating the GenMon Instance
* Conainer 
* Database
* PopRep
* Web-App


# Strategy
For a given OS-user, the deployment must run completely automated. The deployment is implemented in a script that does the complete installation and initialisation. For starting and stopping the GenMon-System separate start- and stop-scripts are written.


# Create New OS User
The first step is to create a new user-accounts at the level of the OS. This can be done using the script 'create_user.sh' from project 'quagzws-htz'. 

```
/home/quagadmin/source/quagzws-htz/bash/create_user.sh -u gnmzws -s /bin/bash -g 'zwsgrp;sudo' -p MbpTD5ZnK8nQ
```

After the first login, the password is changed from the initial value to a different password using the command `passwd`.


# Initialisation
The initialisation process contains all steps that have to be done only one per instance. This consists of all steps that include the installation of all software. The initialisation of an instance is split into two steps.

1. Building the singularity container image
2. Post-Building steps


## Building Container
The container is built using the build-script 'build_gnm_sif.sh' with the following parameter file.

```
./simg/genmon-sidef/bash/build_gnm_sif.sh -p simg/genmon-sidef/par/gnm_config.par &> simg/img/genmon/`date +"%Y%m%d%H%M%S"`_gnm.log
```

The use of a parameter file for the configuration makes it easier to keep the configuration that is common for multiple scripts consistent. With the current setting of having the PopReport repository as a private repository, the clone process asks for username and password. This is solved by converting the PopReport repository as a public repository.


## Start Container Instance
From the image file that was built, the container is started with the bash script `start_si_gnm.sh`. The input is read from the specified parameter file.

```
cd 
./simg/genmon-sidef/bash/start_si_gnm.sh -p simg/genmon-sidef/par/gnm_config.par
```


## Post-Building Steps
The Post-Building steps required for running GenMon are done using the script `post_install_gnm.sh`. 

```
# shell in container
sudo singularity shell --shell /bin/bash instance://gnmsicnt
# run post_install
cd /home/gnmzws/

```



# Starting the GenMon-System
