---
title: "Postprocessing BVCH Pedigree"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Disclaimer
The PopReport results for the BVCH pedigree are postprocessed. 


# Project
The project name is found by 

```
psql -U postgres -d GenMon_CH -c "SELECT datname FROM pg_database where datname like 'PPP%'"
```

From the poprep output, we know that the project name is `PPP_sOIJi5jOrPpzw`


# Tables with PopRep Results
Tables created by PopRep

```
PRPPROJ=PPP_X70k7O8Ev7stQ
psql -U postgres -d $PRPPROJ -c "select * from pg_catalog.pg_tables where tableowner = 'apiis_admin';"
```


# Breed ID
How do we have to determine the breed ID

```
psql -U postgres -d GenMon_CH -c "select * from codes"
```

which is still empty.

Content of species table

```
psql -U postgres -d GenMon_CH -c "select * from species"
```

still empty. The species table seams to related users of the webapp to the different species that will be displayed. Here this does not seam to be important.

Weights

```
psql -U postgres -d GenMon_CH -c "select * from thres_weight"
```

default weights are found.

# Summary

```
psql -U postgres -d GenMon_CH -c "select * from summary"
```


# Postprocessing

Run php from command line

```
cd /home/gnmzws/source/GENMON
php -f PostprocessPopRep.php
```

Output produces

```
PHP Warning:  pg_fetch_result(): Unable to jump to row 0 on PostgreSQL result index 9 in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 39
ERROR:  schema "apiis_admin" does not exist
LINE 1: CREATE TABLE apiis_admin.tmp2_table3 (
                     ^
ERROR:  schema "apiis_admin" does not exist
ERROR:  schema "apiis_admin" does not exist
invalid command \N
invalid command \N
invalid command \N
invalid command \N
invalid command \.
ERROR:  syntax error at or near "119"
LINE 1: 119 1923 1 0.0000 0.0000 0.0000
        ^
PHP Warning:  pg_query(): Query failed: ERROR:  schema "apiis_admin" does not exist in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 90
PHP Warning:  pg_query(): Query failed: ERROR:  relation "tmp2_table3" does not exist in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 94
PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/gnmzws/source/GENMON/logger.php:56) in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 101
```

Find schemas in DB

```
psql -U postgres -d GenMon_CH -c "SELECT schema_name FROM information_schema.schemata"
psql -U geome_admin -d GenMon_CH -c "SELECT schema_name FROM information_schema.schemata"
```

Create new schema

```
psql -U geome_admin -d GenMon_CH -c "CREATE SCHEMA IF NOT EXISTS apiis_admin"
psql -U geome_admin -d GenMon_CH -c "SELECT schema_name FROM information_schema.schemata"
    schema_name     
--------------------
 pg_toast
 pg_temp_1
 pg_toast_temp_1
 pg_catalog
 public
 information_schema
 apiis_admin
(7 rows)

```

Check codes

```
psql -U geome_admin -d GenMon_CH -c "select * from codes"
 db_code | short_name | ext_code |        class         |                     long_name                      
---------+------------+----------+----------------------+----------------------------------------------------
     131 | BV2000     |          | BREED                | Braunvieh2000                   
```



Insert codes

```
psql -U geome_admin -d GenMon_CH -c "insert into codes (db_code, short_name, class, long_name) values(6, 'BV', 'BREED', 'Braunvieh')"
```

Check codes after insert

```
psql -U geome_admin -d GenMon_CH -c "select * from codes"
 db_code | short_name | ext_code |        class         |                     long_name                      
---------+------------+----------+----------------------+----------------------------------------------------
       6 | BV         |          | BREED                | Braunvieh                                         
(1 row)

```

Weights for the different indices

```
psql -U geome_admin -d GenMon_CH -c "select * from thres_weight"
        criteria         |  t1  |  t2  | weight | crit_type |  owner  | species 
-------------------------+------+------+--------+-----------+---------+---------
 percent_change_wsl      |   94 |  100 |    0.2 | SocioEco  | default | 
 percent_farmer          |    1 |   16 |    0.1 | SocioEco  | default | 
 ne                      |   50 |  250 |    0.4 | demo      | default | 
 percent_grazing_surface |    6 |   30 |   0.15 | SocioEco  | default | 
 cryo_cons               |    0 |    1 |    0.1 | final     | default | 
 avg_inb                 |  0.1 | 0.03 |   0.15 | demo      | default | 
 percent_less_19         |    3 |   10 |   0.05 | SocioEco  | default | 
 index_demo              |    0 |    1 |    0.5 | final     | default | 
 trend_females           |   -5 |    0 |   0.15 | demo      | default | 
 index_socio_eco         |    0 |    1 |    0.1 | final     | default | 
 percent_more_65         |   20 |    4 |   0.15 | SocioEco  | default | 
 introgression           | 0.15 | 0.03 |   0.15 | final     | default | 
 unemployment_rate       |    5 |    2 |      0 | SocioEco  | default | 
 breed_cultural_value    |    0 |    1 |    0.1 | SocioEco  | default | 
 min_radius              |   20 |   50 |   0.15 | final     | default | 
 trend_females           |   -5 |    0 |   0.15 | demo      | blw     | Cattle
 breed_num_farms_trend   |   -5 |    0 |    0.1 | SocioEco  | default | 
 demog_balance           |    0 |    3 |   0.05 | SocioEco  | default | 
 evol_job_primary_sector |    0 |   10 |    0.1 | SocioEco  | default | 
 trend_males             |   -5 |    0 |   0.15 | demo      | default | 
 ped_compl               |   87 |   97 |   0.15 | demo      | default | 
(21 rows)

```

From the existing installation

```
psql -U geome_admin -d GenMon_CH -c "select * from thres_weight where owner = 'default'"
```


Next trial for postprocessing

```
Singularity> cd /home/gnmzws/source/GENMON
Singularity> php -f PostprocessPopRep.php

PHP Warning:  pg_fetch_result(): Unable to jump to row 0 on PostgreSQL result index 10 in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 55
pg_dump: [archiver (db)] connection to database "apiis_admin" failed: FATAL:  database "apiis_admin" does not exist
PHP Warning:  pg_query(): Query failed: ERROR:  relation "apiis_admin.tmp2_table3" does not exist in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 90
PHP Warning:  pg_query(): Query failed: ERROR:  relation "tmp2_table3" does not exist in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 94
ls: cannot access '/var/lib/postgresql/projects//*.pdf': No such file or directory
mv: missing destination file operand after '/var/www/html/genmon-ch/pdf/error-BV.pdf'
Try 'mv --help' for more information.
rm: cannot remove '/var/lib/postgresql/projects/': Device or resource busy
dropdb: missing required argument database name
Try "dropdb --help" for more information.
PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/gnmzws/source/GENMON/logger.php:56) in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 101
```

# Drop Databases
The following command allows to delete a database

```
dropdb -U apiis_admin -w PPP_CLBgBYyker8lM
dropdb -U apiis_admin -w PPP_Zu57A2p0UPLEU
```


# Problems

## P1: Empty project name
Project cannot be found

```
psql -U geome_admin -d GenMon_CH -c "SELECT * FROM pg_database"
```

Most likely the database for the project was aready deleted.

## Solution
Re-run analysis for BV

```
/home/gnmzws/simg/genmon-sidef/bash/run_poprep.sh \
-b BV \
-p /home/gnmzws/simg/genmon-sidef/par/gnm_config.par \
-d /home/gnmzws/gnm/prpinput/PopReport_Braunvieh_20210325.csv_adaptfin7.csv -Z &> /home/gnmzws/gnm/prplog/`date +"%Y%m%d%H%M%S"`_prp.log
```


# Testing Postprocessing Script
A test script for the postprocessing is created. This is executed to run some tests.

```
cd /home/gnmzws/source/GENMON
php -f TestPostprocessPopRep.php
```


# Running Complete Postprocessing Script

Error

```
php -f PostprocessPopRep.php



PHP Warning:  pg_query(): Query failed: ERROR:  type "method" does not exist
LINE 1: ...TE summary SET ne=(select ne from breed6_ne where method 'Ne...
                                                             ^ in /home/gnmzws/source/GENMON/PostprocessPopRep.php on line 439
```

Debugging sql statement

```
psql -U geome_admin -d GenMon_CH -c "select * from breed6_ne"
```

Check on table with NE

```
PRPPROJ=PPP_X70k7O8Ev7stQ
psql -U apiis_admin -d $PRPPROJ -c "select * from tmp2_ne"
  method   | ne  | description 
------------+-----+-------------
 Ne_DeltaFg | 136 |  
 Ne_Deltafg | 208 |  
(2 rows)

```

# Results in Summary Table 
Check the summary table

```
psql -U geome_admin -d GenMon_CH -c "select * from summary"
```


# Corrected Pedigree
The pedigree was corrected by adapting the introgression coefficients. Hence, the pedigree must be re-analysed.

```
/home/gnmzws/simg/genmon-sidef/bash/run_poprep.sh \
-b BV \
-p /home/gnmzws/simg/genmon-sidef/par/gnm_config.par \
-d /home/gnmzws/gnm/prpinput/PopReport_BV_20210510.csv_conv.csv_adaptfin7.csv -Z &> /home/gnmzws/gnm/prplog/`date +"%Y%m%d%H%M%S"`_prp.log

```

# Inspect Results
The first step is to find out the name of the project under which the pedigree was analysed in PopReport. This can be seen from the directory namens under `/var/lib/postgres/projects`

```
# assign to variable
PROJNAME=$(ls -1tr /home/gnmzws/gnm/bindroot/projects | tail -1)
echo $PROJNAME
```

The project database with all the PopReport results is obtained by the following statement

```{bash}
psql -U postgres -d GenMon_CH -c "SELECT datname FROM pg_database where datname = '$PROJNAME'"

#      datname      
#-------------------
# PPP_NJbjmWSmjuVRo
#(1 row)

```

Run the PHP postprocessing script step-by-step by first creating the SQL-script `PostprocessPopRep.sql` 

```{bash}
# start interactive version of psql client
psql -U geome_admin -d GenMon_CH

-- terminate the client
GenMon_CH=# \q
```


Run a bash version (`PostprocessPopRep.sh`) of the PHP postprocessing script `PostprocessPopRep.php` 

```{bash}
source PostprocessPopRep.sh

```


