---
title: "On Variables and Scripts"
author: "Peter von Rohr"
date: "6/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disclaimer
Experiments and tests on scripts and variables. Variables that are defined on different levels are not always passed from one script to next script when they are passed via commandline arguments.


## Experiments and Tests
Two alternatives are tested

1. sourcing the second script from the first: Leads to problem that command-line arguments are not passed to second script.
2. calling second script from first: variables defined in first script are not available in second script.
3. todo: export variables from first script and check whether they are available.

## Results
When calling a script from a different script, the environment variables defined in the first script by simple assignment are not available in the second script. An alternative would be to source the second script instead of calling it. But that prevents us to pass command-line arguments to the second script. 

Variables are available through a sequence of scripts when exporting the variable in addition to the definition by simple assignment. Hence the following contruct

```
APIIS_HOME=${P_APIISHOME:-'/home/popreport/production/apiis'};export APIIS_HOME
```

makes the variable 'APIIS_HOME' available for all script that are called subsequently. This can also be done in .bashrc. When exporting the variable 'APIIS_HOME' in .bashrc, then it is available in all processes that are created newly. 


## Note
The construct with assignment of default values to variable names does not work as done in poprep scripts. In those scripts a colon is missing. Hence assignments like

```
APIIS_HOME=${P_APIISHOME-'/home/popreport/production/apiis'}
```

must be replaced by 

```
APIIS_HOME=${P_APIISHOME:-'/home/popreport/production/apiis'}
```


