---
title: "Installation of PopRep"
author: "Peter von Rohr"
date: "6/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disclaimer
Documentation and protocol for installing PopRep.


## Download
PopRep was downloaded as shown in the download protocol in '20200528_download_poprep'. The downloaded tar-ball contains a complete linux distribution. We try to use the installation description for GenMon to find the relevant parts of PopRep.


## Installation
Based on the description in `install.html`

```
cdpgp
open GENMON_GitHub/GENMON/install.html
```


## Container
We start by building a separate container for PopRep.


### Initialise Working Directory
The container image file is built in a working directory which is created by the following script.

```
cd /home/quagadmin/simg/img/
../genmon-sidef/bash/init_simg.sh -w `pwd`/poprep
```

### Sandbox Container
For testing and debugging purposes, it is convenient to have a container sandbox directory in which we can test different solutions.

Building a sandbox container 

```
sudo singularity build --sandbox ubuntu_sand docker://ubuntu:18.04
```

Open a shell in the sandbox

```
sudo singularity shell --writable ubuntu_sand
```

### Packages 
Packages required for poprep but were installed earlier in the installation description


```
apt-get update -y
apt-get install -y vim build-essential sudo git apt-utils software-properties-common curl gdebi-core
# locales
apt-get install -y locales
locale-gen en_US.UTF-8
locale-gen de_CH.UTF-8
  
export DEBIAN_FRONTEND=noninteractive
apt-get install -y tzdata
# set your timezone
echo 'Europe/Berlin' > /etc/timezone

# pg
apt-get install -y postgresql

```


Adding the packages needed by poprep as shown in the description. 

```
apt-get update -y
apt-get install -y texlive-full
apt-get install -y texinfo  
apt-get install -y gnuplot
#apt-get install -y pdftk
apt-get install -y zip
apt-get install -y unzip
apt-get install -y gfortran
apt-get install -y transfig
apt-get install -y xinetd
```

The package `pdftk` is not available for ubuntu bionic (18.04), it is installed via a separate procedure

```
  # special installation for pdftk which is no longer available
  curl -sSL http://launchpadlibrarian.net/337429932/libgcj-common_6.4-3ubuntu1_all.deb > libgcj-common_6.4-3ubuntu1_all.deb
  curl -sSL http://launchpadlibrarian.net/340410966/libgcj17_6.4.0-8ubuntu1_amd64.deb > libgcj17_6.4.0-8ubuntu1_amd64.deb
  curl -sSL http://launchpadlibrarian.net/277739894/pdftk_2.02-4build1_amd64.deb > pdftk_2.02-4build1_amd64.deb
  gdebi --n libgcj-common_6.4-3ubuntu1_all.deb
  gdebi --n libgcj17_6.4.0-8ubuntu1_amd64.deb
  gdebi --n pdftk_2.02-4build1_amd64.deb
  apt-get update
  rm -rf libgcj-common_6.4-3ubuntu1_all.deb libgcj17_6.4.0-8ubuntu1_amd64.deb pdftk_2.02-4build1_amd64.deb
```

Configure papersize

```
#sudo vim /etc/papersize #change the default paper size in latex
#a4 (instead of letter; + Esc + ZZ (to save))
sed -i 's/letter/a4/' /etc/papersize
paperconfig -p a4
```

Copy the PopRep code into the container. This is done via the '%files' directive in the singularity recipe file. 


### Packages for PopRep
The packages to be installed for PopRep are taken from the README.install inside of PopRep. This leads to a smaller image file.


## Alternative Running Mode
From 'PopRep.php' (in GENMON_GitHub/GENMON), it becomes clear that an uploaded pedigree file is processed via the command 

```
/home/popreport/production/apiis/bin/./process_uploads.sh -i /var/lib/postgresql/incoming -l /var/log/popreport.log -u www-data -g www-data -a /home/popreport/production/apiis
```

This command should be usable for a different user such as zws. The question at this point is how to start the DB-server inside of the singularity container image. The same question must be solved for the container containing TheSNPpit. 






