---
title: GenMon Analysis Second Round
author: pvr
date: "2022-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Disclaimer
Description of steps to be done for second round of data analysis.


# Current Infrastrucutre Setup
The GenMon system runs on the rented server `fagr.genmon.ch`. On that server there are two admin-accounts. See KpX-file for details. 

Based on the ouput of 

```bash
sudo singularity instance list
# INSTANCE NAME    PID      IP              IMAGE
# gnmsicnt         16203                    /home/gnmzws/simg/img/genmon/gnm.sif
# signm            2478     10.22.0.40      /home/quagadmin/simg/img/genmon/gnm.sif
```

The container `signm` runs the container that is accessible via the web-interface. 
shows that there are two singularity containers running. 


# Tests
On the tutorial page `https://fagr.genmon.ch/gnm/genmon-ch/tutorial.php` there is a link to a test dataset (`https://fagr.genmon.ch/gnm/genmon-ch/pdf/data_sample.csv`) which can be used to validate the results. 

This test dataset is downloaded with 

```bash
mkdir -p inst/extdata/gnm_test_data
cd inst/extdata/gnm_test_data/
wget https://fagr.genmon.ch/gnm/genmon-ch/pdf/data_sample.csv
head -3 data_sample.csv 
# #animal|sire|dam|birth_date|sex|plz|introg|inb_gen|cryo
# 433||328|1988-01-01|F|4703|0.03||
# 653|422||1994-01-01|F|2345|0.14||
```

This test dataset can be uploaded to the GenMon website. The first requirements for that is to add a new breed. We are doing that with a test breed for cattle and we name it `tbc2022`. It is important to not have an underscore in the short name, otherwise the links to the reports are not going to work.


# GenMon Analysis Workflow
This section describes how an analysis of a pedigree in GenMon is organized. The analysis is organized in several steps. 


## Step 1: Data Upload
The data is uploaded from the details-page of the created breed to be analysed. In an alterative version this interactive data-upload can be replaced by command-line version with `scp`. 


## Step 2: PopRep
The uploaded pedigree data is analysed with PopRep. In the web-version the PopRep analysis is started from within the file `/var/www/html/genmon-ch/PopRep.php`. In that file the command that starts the analysis is 

```bash
exec('export APIIS_HOME=/home/popreport/production/apiis;/home/popreport/production/apiis/bin/./process_uploads.sh -i /var/lib/postgresql/incoming -l /home/quagadmin/gnm/gnmlog/popreport.log -u www-data -g www-data -a /home/popreport/production/apiis');
```

The script `process_uploads.sh` requires a parameterfile which contains properties of the uploaded data. This is generated by `/var/www/html/genmon-ch/GenStuDb.php`. Furthermore, in `process_uploads.sh` the PopReport analysis is started with `$APIIS_HOME/bin/run_popreport_file`. 

In `run_popreport_file` the project-specific database is created and a basic structure is imported into that database. From `run_popreport_file` the three parts of the PopReport analysis are done. Each of these parts will produce a pdf-report. The three parts are 

1. handle_pedi_file
2. run_popreport and
3. PRMON_MONITOR

The script `genmon-sidef/bash/run_poprep.sh` seams to be able to run a complete PopRep analysis. This was already done on `fagr.genmon.ch` as user `gnmzws` as shown below. 

```bash
/home/gnmzws/simg/genmon-sidef/bash/run_poprep.sh -b BV -p /home/gnmzws/simg/genmon-sidef/par/gnm_config.par -d /home/gnmzws/gnm/prpinput/PopReport_BV_20210510.csv_conv.csv_adaptfin7.csv -Z &> /home/gnmzws/gnm/prplog/`date +"%Y%m%d%H%M%S"`_prp.log
```

A new test with this script is done via

```bash
TDATE=$(date +"%Y%m%d%H%M%S")
PEDPATH=/home/gnmzws/simg/genmon-sidef/inst/extdata/gnm_test_data/data_sample.csv
BREED=tbc2022
PRPPROJPATH=/home/gnmzws/gnm/prp_projects/${TDATE}_$BREED
/home/gnmzws/simg/genmon-sidef/bash/run_poprep.sh -b $BREED \
-d $PEDPATH \
-p /home/gnmzws/simg/genmon-sidef/par/gnm_config.par \
-r $PRPPROJPATH \
-Z &> /home/gnmzws/gnm/prplog/${TDATE}_prp.log
```

The new call after inserting project dir generation based on starting time and breed name by default

```bash
PEDPATH=/home/gnmzws/simg/genmon-sidef/inst/extdata/gnm_test_data/data_sample.csv
BREED=tbc2022
/home/gnmzws/simg/genmon-sidef/bash/run_poprep.sh -b $BREED \
-d $PEDPATH \
-p /home/gnmzws/simg/genmon-sidef/par/gnm_config.par \
-Z &> /home/gnmzws/gnm/prplog/${TDATE}_prp.log
```

This analysis makes it possible to extract the name of the database. 

All old databases are listed by 

```bash
CURDB=PPP_xmKDvyg6exqF2
psql -U postgres -l | grep PPP | grep -v "$CURDB" | cut -d ' ' -f2
```

This list can be deleted by

```bash
for db in $(psql -U postgres -l | grep PPP | grep -v "$CURDB" | cut -d ' ' -f2)
do
  echo " * Drop db: $db ..."
  dropdb -p 5434 -U postgres $db
  sleep 2
done
```

Find the list of tables for a given database

```bash
CURDB=PPP_xmKDvyg6exqF2
psql -U postgres -d $CURDB -c "SELECT * FROM pg_catalog.pg_tables"
```

The tables produced by PopRep are owned by 'apiis_admin'

```bash
CURDB=PPP_xmKDvyg6exqF2
psql -U postgres -d $CURDB -c "SELECT * FROM pg_catalog.pg_tables WHERE tableowner = 'apiis_admin'"
```

Looking at a given table can be done with

```bash
CURDB=PPP_xmKDvyg6exqF2
psql -U postgres -d $CURDB -c "SELECT * FROM apiis_admin.animal"
```


## Step 3: Indices from PopRep Results
From the php-code, we have to find out what tables are used to compute which index.





# TODO

## Problem 1: No global index
For the test dataset no global index is produced because some of the partial indices are missing


