---
title: "Singularity Container For GENMON"
author: "Peter von Rohr"
date: "5/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Disclaimer
The steps to setup a singularity container for the GENMON project is described.


# Prerequisites
All material is inclosed in the github repository `genmon-sidef`. A shell script is provided to clone and to update the content of the github repository. The first time the repository must be cloned.

```
./bash/clone_genmon_sidef.sh
```

After the initial cloning steps, all updates must be deployed using 

```
./bash/update_genmon_sidef.sh
```


# Plan
Start with a singularity sandbox container built according to the description given in 

* https://www.youtube.com/watch?v=m8llDjFuXlc and 
* https://www.youtube.com/watch?v=SJHizTjwyFk.


# Protocol
## Initialise working directory

```
SIMGWD=/home/quagadmin/simg/img/genmon
./simg/genmon-sidef/bash/init_simg.sh -w $SIMGWD
```

## Building the container

```
SIMGWD=/home/quagadmin/simg/img/genmon;cd $SIMGWD
sudo singularity build --sandbox ubuntu_sand docker://ubuntu:18.04
```

## Start shell in Sandbox Container

```
sudo singularity shell --writable ubuntu_sand/
```


## Apply the required changes
The changes are taken from the file 'install.html' from the github repository.


### Server Basics
Additional packages are installed using 'apt-get'

```
apt-get update
apt-get install -y vim build-essential sudo git
```

At this point it is not clear whether 'apache2' must be installed also


### Firewall 
The firewall settings are done on the host. When starting an instance port-forwarding must be considered.


### Postgres

```
# locales
apt-get install -y locales
locale-gen en_US.UTF-8
locale-gen de_CH.UTF-8

#install tzdata package
export DEBIAN_FRONTEND=noninteractive
apt-get install -y tzdata
# set your timezone
echo 'Europe/Berlin' > /etc/timezone

# pg
apt-get install -y postgresql
```

The result at the end of the installation

```
Success. You can now start the database server using:

    /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start

```



### Postgis

```
apt-get install -y postgresql-10-postgis-2.4
```

### Config DB

First, the database server must be started by

```
sudo -i -u postgresql
/usr/lib/postgresql/10/bin/initdb -D /var/lib/postgresql/10/data -A trust -U postgres
mkdir -p /var/lib/postgresql/10/log
/usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/data -l /var/lib/postgresql/10/log/logfile start
```

Then the DB-user can be created as
```
sudo -i -u postgres
createuser -s -P geome_admin # ==> must enter pwd twice which should be 'geome'
```

Creating a new database

```
createdb -O geome_admin GenMon_CH
```

Create postgis extension

```
psql -d GenMon_CH -c "CREATE EXTENSION postgis;"
```



## Singularity Recipe
All the changes are recorded as statements in a singularity recipe file.
