---
title: "Effective Population Size"
author: "Peter von Rohr"
date: "11/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disclaimer
This protocol contains material that helps to understand how the entries in the summary table of effective population size can be influenced.


## Background
The effective population size is computed by poprep and shown in the summary table. The content of the summary table is 

```
psql -U geome_admin -d GenMon_CH -c "SELECT * FROM summary where owner='zwsgnm';"
```

The effective population size is stored in the column `ne`. But this field can be changed on the page `breed_detail.php`. With that also all the indices are changed. 


## Effective Population Size
The effective population size (Ne) as computed by poprep is obtained by 

```
psql -U geome_admin -d GenMon_CH -c "SELECT * FROM breed11_ne;"
```

The correct statement for selecting the value of Ne

```
psql -U geome_admin -d GenMon_CH -c "SELECT Ne FROM breed11_ne where method = 'Ne_DeltaFp';"
```


## Solution
The value for effective population size (Ne) in the summary table for each breed is no longer taken from the radio-buttons on `breed-detail.php` but it is taken from the table `breed<breed_id>_ne`. This change is implemented in `breed_detail.php`. In `index.php` no changes are implemented, except for the former deprecation of the display of the ranges. 

